/** S19 override: AUTHORITY 規則集 */
import type { InterpretationRule } from "../../interpretationRuleTypes.js";

export const AUTHORITY_RULES: InterpretationRule[] = [
  {
    id: "tianliang-lu-authority",
    star: "天梁",
    transform: "祿",
    palace: "父母宮",
    title: "上層支持",
    baseWeight: 1.1,
    eventType: ["老闆", "支持", "制度", "保護"],
    baseScenarios: [
      "上層或長輩會給支持",
      "制度或規則站在你這邊",
      "遇到問題容易有人罩",
    ],
    positiveScenarios: [
      "有利穩住局面",
      "有貴人型支持",
    ],
    negativeScenarios: ["也可能過度依賴上層，忽略自主節奏"],
    narrative: "不是你一個人在撐，有上面的力量在幫你。",
    actionHint: "該用資源時就用。",
  },
  {
    id: "tianliang-ji-authority",
    star: "天梁",
    transform: "忌",
    palace: "父母宮",
    title: "制度壓力",
    baseWeight: 1.3,
    eventType: ["制度", "限制", "壓力", "責任"],
    baseScenarios: [
      "制度或上層會變成壓力來源",
      "容易被規則卡住",
      "長輩或主管期待會變重",
    ],
    positiveScenarios: ["若能釐清規則邊界，仍有迴旋空間"],
    negativeScenarios: [
      "有被綁住或被限制的感覺",
      "責任增加但彈性降低",
    ],
    narrative: "不是事情難，而是規則讓事情變難。",
    actionHint: "先理解規則，再找空間。",
  },
  {
    id: "taiyang-lu-authority",
    star: "太陽",
    transform: "祿",
    palace: "父母宮",
    title: "被看見與提拔",
    baseWeight: 1.1,
    eventType: ["老闆", "曝光", "提拔", "信任"],
    baseScenarios: [
      "容易被上層看見",
      "有被提拔或信任的機會",
      "角色可能被放大",
    ],
    positiveScenarios: ["有升職或重要任務機會"],
    negativeScenarios: ["曝光同時也可能伴隨更高期待與壓力"],
    narrative: "你會被放到更前面的位置。",
    actionHint: "準備好承接責任。",
  },
  {
    id: "taiyang-ji-authority",
    star: "太陽",
    transform: "忌",
    palace: "父母宮",
    title: "上層壓力放大",
    baseWeight: 1.3,
    eventType: ["老闆", "壓力", "評價", "責任"],
    baseScenarios: [
      "上層壓力變大",
      "容易被盯或被要求",
      "評價壓力上升",
    ],
    positiveScenarios: ["若能主動對齊期待，有機會降低誤判"],
    negativeScenarios: [
      "容易被誤解或被放大檢視",
      "責任感過重",
    ],
    narrative: "壓力來自上面，而不是事情本身。",
    actionHint: "先穩住，再回應。",
  },
  {
    id: "ziwei-quan-authority",
    star: "紫微",
    transform: "權",
    palace: "父母宮",
    title: "權力互動",
    baseWeight: 1.1,
    eventType: ["權力", "位置", "決策", "上層互動"],
    baseScenarios: [
      "你與上層之間的權力互動會變明顯",
      "需要面對決策與責任",
      "位置感變強",
    ],
    positiveScenarios: ["有機會進入核心決策"],
    negativeScenarios: ["容易有壓力或對抗感"],
    narrative: "你不只是執行者，而是開始碰到權力層。",
    actionHint: "看清位置，再做反應。",
  },
  {
    id: "jumen-ji-authority",
    star: "巨門",
    transform: "忌",
    palace: "父母宮",
    title: "上層誤解",
    baseWeight: 1.3,
    eventType: ["誤會", "溝通", "上層關係"],
    baseScenarios: [
      "與上層溝通容易出現落差",
      "你說的與對方理解的不同",
      "容易有誤會或認知差",
    ],
    positiveScenarios: ["若願意書面摘要與二次確認，有機會對齊"],
    negativeScenarios: [
      "容易被誤解或被錯判",
      "溝通成本變高",
    ],
    narrative: "問題不一定是做錯，而是被理解錯。",
    actionHint: "重要的事要講兩次。",
  },
];

/** 僅 override 規則（不含 seed），僅在 S19 trigger 宮位使用 */
