/** S19 override: CAREER 規則集 */
import type { InterpretationRule } from "../../interpretationRuleTypes.js";

export const CAREER_RULES: InterpretationRule[] = [
  {
    id: "tianliang-lu-career",
    star: "天梁",
    transform: "祿",
    palace: "官祿宮",
    title: "專業庇護",
    baseWeight: 1.1,
    eventType: ["工作", "專業", "貴人", "職場保護"],
    baseScenarios: [
      "工作上容易得到保護與支援",
      "靠專業、制度、經驗能穩住事情",
      "容易有資深者、規則體系或既有口碑在幫你",
    ],
    positiveScenarios: ["容易被信任、被倚重", "有逢凶化吉或被罩住的傾向"],
    negativeScenarios: ["也可能過度依賴原有優勢，不想調整"],
    narrative: "這是一種靠專業、資歷與制度撐住場面的力量。",
    actionHint: "把你的穩定，變成可被看見的價值。",
  },
  {
    id: "tianliang-ji-career",
    star: "天梁",
    transform: "忌",
    palace: "官祿宮",
    title: "責任壓身",
    baseWeight: 1.3,
    eventType: ["工作", "責任", "名聲壓力", "制度困住"],
    baseScenarios: [
      "工作上容易背責任、扛壓力",
      "制度、流程或權責分配可能變成限制",
      "容易有被拖累或被綁住的感覺",
    ],
    positiveScenarios: ["若處理得當，能建立新的邊界與定位"],
    negativeScenarios: [
      "容易被責任與形象綁架",
      "若外部壓力再疊，可能出現疲乏與想抽離",
    ],
    narrative: "你能扛，但也容易因為太能扛而把自己卡住。",
    actionHint: "先劃清責任，再談承擔。",
  },
  {
    id: "wenchang-ke-career",
    star: "文昌",
    transform: "科",
    palace: "官祿宮",
    title: "文書與制度到位",
    baseWeight: 1.1,
    eventType: ["工作", "制度", "簽約", "評核"],
    baseScenarios: [
      "適合做文件、流程、規劃與整理",
      "有利評核、簡報、申請、簽約或正式提案",
      "事情更容易被制度承認",
    ],
    positiveScenarios: ["容易拿到正式認可", "有升職、評價變好、專業被看見的可能"],
    negativeScenarios: ["文書過關不等於執行無誤，後續仍要落地"],
    narrative: "這是把事情講清楚、寫清楚、規則化的好時機。",
    actionHint: "把流程補齊，比衝刺更重要。",
  },
  {
    id: "wenchang-ji-career",
    star: "文昌",
    transform: "忌",
    palace: "官祿宮",
    title: "文件與溝通出錯",
    baseWeight: 1.2,
    eventType: ["工作", "文書失誤", "溝通卡關", "誤會"],
    baseScenarios: [
      "資訊落差、訊息漏接或理解不同容易出問題",
      "文書、合約、簡報或說法細節需要特別注意",
      "容易因一個小細節拖累整體進度",
    ],
    positiveScenarios: ["若提早檢查，錯誤可轉成修正機會"],
    negativeScenarios: ["嚴重時可能影響評價、合作或進度", "有被誤解、背鍋或說不清的感覺"],
    narrative: "問題不一定大，但很可能小地方出錯，最後變成大問題。",
    actionHint: "二次確認，比自信更重要。",
  },
  {
    id: "taiyang-lu-career",
    star: "太陽",
    transform: "祿",
    palace: "官祿宮",
    title: "曝光與責任帶來機會",
    baseWeight: 1.1,
    eventType: ["工作", "曝光", "責任", "升遷機會"],
    baseScenarios: [
      "工作上的可見度提高",
      "責任變多，但也因此帶來機會",
      "容易被看見、被期待、被交辦",
    ],
    positiveScenarios: ["有升遷、主責、對外代表的機會", "容易因承擔而獲得信任"],
    negativeScenarios: ["太多曝光也可能讓壓力上身"],
    narrative: "這是一種因為站到台前、扛起責任，而被看見的機會。",
    actionHint: "能見度上來時，也要顧好續航力。",
  },
  {
    id: "taiyang-ji-career",
    star: "太陽",
    transform: "忌",
    palace: "官祿宮",
    title: "付出與名聲壓力",
    baseWeight: 1.3,
    eventType: ["工作", "壓力", "責任過重", "評價風險"],
    baseScenarios: [
      "付出與責任感特別重，但不一定有對等回報",
      "容易感覺一直在扛、一直在被要求",
      "對外評價、表現與角色壓力會變明顯",
    ],
    positiveScenarios: ["若主動調整節奏，有機會重新界定角色邊界"],
    negativeScenarios: [
      "容易出現疲累、被消耗、被看不順眼或被放大檢視",
      "嚴重時會有不想再撐下去的感覺",
    ],
    narrative: "你不是沒能力，而是被太多外部期待和責任拖住了。",
    actionHint: "先守住界線，再談表現。",
  },
  {
    id: "ziwei-quan-career",
    star: "紫微",
    transform: "權",
    palace: "官祿宮",
    title: "角色主導上升",
    baseWeight: 1.0,
    eventType: ["工作", "主導", "決策", "掌舵"],
    baseScenarios: [
      "工作裡更需要你出面做決定",
      "角色位置上升，責任也跟著上升",
      "你會更想掌控局面",
    ],
    positiveScenarios: ["有帶隊、主責、上位或做核心決策的機會"],
    negativeScenarios: ["若局勢混亂，容易變成什麼都要你扛"],
    narrative: "事情會更需要你來定調，主導感與責任感一起上升。",
    actionHint: "主導可以，但不要把所有事都攬過來。",
  },
];

