/** S19 override: FORTUNE 規則集 */
import type { InterpretationRule } from "../../interpretationRuleTypes.js";

export const FORTUNE_RULES: InterpretationRule[] = [
  {
    id: "tiantong-lu-fortune",
    star: "天同",
    transform: "祿",
    palace: "福德宮",
    title: "內在緩衝變強",
    baseWeight: 1.1,
    eventType: ["情緒", "恢復", "休息", "幸福感"],
    baseScenarios: [
      "情緒比較容易被安撫與緩衝",
      "內在狀態有比較多喘息空間",
      "比較容易找到讓自己舒服一點的節奏",
    ],
    positiveScenarios: ["有利休息、修復、調整生活節奏", "容易感受到被照顧、被接住或至少沒那麼緊"],
    negativeScenarios: ["也可能變得想躲、想懶、想暫時不面對"],
    narrative: "這是一種內在有緩衝、有軟墊，不容易一下就崩的狀態。",
    actionHint: "有喘息空間時，先把自己補回來。",
  },
  {
    id: "tiantong-ji-fortune",
    star: "天同",
    transform: "忌",
    palace: "福德宮",
    title: "內耗與鬆散",
    baseWeight: 1.2,
    eventType: ["情緒", "內耗", "逃避", "倦怠"],
    baseScenarios: [
      "容易覺得提不起勁、想逃、想躲或不想面對",
      "情緒容易悶在裡面，變成一種鈍鈍的消耗",
      "看起來沒事，實際上恢復力在下降",
    ],
    positiveScenarios: ["若能停下來整理，反而能看見自己真正累在哪"],
    negativeScenarios: [
      "容易出現拖延、倦怠、情緒性放空",
      "若壓力再疊，可能進入更明顯的低潮或失去動力",
    ],
    narrative: "這種累不是爆炸型，而是慢慢鬆掉、慢慢耗掉。",
    actionHint: "先承認自己累了，再談效率。",
  },
  {
    id: "taiyin-lu-fortune",
    star: "太陰",
    transform: "祿",
    palace: "福德宮",
    title: "內在安定感回來",
    baseWeight: 1.1,
    eventType: ["情緒", "安定", "休息", "療癒"],
    baseScenarios: [
      "內在比較容易安靜下來",
      "情緒與休息品質有機會改善",
      "你會更想待在舒服、安全、熟悉的環境裡",
    ],
    positiveScenarios: ["有利休養、修復、睡眠與情緒穩定", "比較容易重新感受到被安放"],
    negativeScenarios: ["若太過退回舒適區，也可能變得不想面對外界"],
    narrative: "這是一種把心收回來、把自己安放好的能量。",
    actionHint: "先把自己安穩下來，再處理外面的事。",
  },
  {
    id: "taiyin-ji-fortune",
    star: "太陰",
    transform: "忌",
    palace: "福德宮",
    title: "失望感累積",
    baseWeight: 1.2,
    eventType: ["情緒", "失望", "退縮", "低落"],
    baseScenarios: [
      "容易感到失望、沒被理解、心裡空掉",
      "表面平靜，但內在退縮感會變強",
      "一些難過與委屈可能不會直接說出來",
    ],
    positiveScenarios: ["若能好好照顧自己，這會變成一次深層整理"],
    negativeScenarios: [
      "容易越來越不想說、不想連結、不想靠近",
      "若壓力持續，可能進入情緒低潮期",
    ],
    narrative: "真正消耗你的，不一定是外面的事，而是心裡那種慢慢退掉的感覺。",
    actionHint: "別只忍著，把委屈找到出口。",
  },
  {
    id: "jumen-lu-fortune",
    star: "巨門",
    transform: "祿",
    palace: "福德宮",
    title: "想通與看清",
    baseWeight: 1.0,
    eventType: ["思考", "釐清", "內在整理", "理解"],
    baseScenarios: [
      "內在思緒變多，但也有機會看清很多事",
      "適合整理自己的想法、疑問與判斷",
      "一些原本說不清的感受，可能慢慢有語言",
    ],
    positiveScenarios: ["容易想通、看清、釐清真正卡點"],
    negativeScenarios: ["想很多的同時，也可能有點停不下來"],
    narrative: "這是一種透過想清楚、說清楚，讓內在慢慢打開的能量。",
    actionHint: "把腦中的雜音寫下來，會比一直想有用。",
  },
  {
    id: "jumen-ji-fortune",
    star: "巨門",
    transform: "忌",
    palace: "福德宮",
    title: "心裡很多話",
    baseWeight: 1.3,
    eventType: ["內耗", "懷疑", "焦慮", "想太多"],
    baseScenarios: [
      "容易在心裡反覆想、反覆懷疑、反覆對話",
      "很多話沒說出口，但在內心轉不停",
      "焦慮與不信任感容易變成精神消耗",
    ],
    positiveScenarios: ["若願意梳理，反而能找到自己真正的不安來源"],
    negativeScenarios: [
      "容易想太多、睡不好、腦袋停不下來",
      "嚴重時會讓心情與判斷一起變鈍",
    ],
    narrative: "累你的不只是事件，而是心裡那個一直停不下來的聲音。",
    actionHint: "先停掉內心辯論，才有空間休息。",
  },
  {
    id: "wenqu-ke-fortune",
    star: "文曲",
    transform: "科",
    palace: "福德宮",
    title: "情緒被整理",
    baseWeight: 1.0,
    eventType: ["情緒", "表達", "整理", "修復"],
    baseScenarios: [
      "情緒比較有機會被整理、被說清楚",
      "適合透過書寫、談話、藝術或儀式感修復自己",
      "比較容易把混亂的感受慢慢收回來",
    ],
    positiveScenarios: ["有利修復心情、重新找回美感與秩序"],
    negativeScenarios: ["也可能停留在表面平靜，深處仍要慢慢消化"],
    narrative: "這是一種把情緒慢慢梳順、讓內在回到比較柔軟節奏的能量。",
    actionHint: "用適合你的方式，把感受整理出來。",
  },
  {
    id: "wenqu-ji-fortune",
    star: "文曲",
    transform: "忌",
    palace: "福德宮",
    title: "情緒糾結",
    baseWeight: 1.2,
    eventType: ["情緒", "糾結", "低落", "脆弱"],
    baseScenarios: [
      "情緒容易被某些細節勾住，放不太下",
      "容易想起遺憾、失落或說不清的感受",
      "內在會有一種卡著、化不開的感覺",
    ],
    positiveScenarios: ["若願意面對，反而能看見自己真正需要安撫的地方"],
    negativeScenarios: [
      "容易一邊壓著、一邊又反覆被觸發",
      "若外界再刺激，會更容易情緒化",
    ],
    narrative: "這種卡不是外面壓你，而是心裡有些東西還沒真正過去。",
    actionHint: "先安撫自己，不要急著逼自己想開。",
  },
  {
    id: "tiangji-quan-fortune",
    star: "天機",
    transform: "權",
    palace: "福德宮",
    title: "腦袋停不下來",
    baseWeight: 1.1,
    eventType: ["思考", "計畫", "焦慮", "精神活動"],
    baseScenarios: [
      "腦袋會特別活躍，很多事都想自己想清楚",
      "容易進入規劃、判斷、分析模式",
      "精神活動增加，但也比較難真的放鬆",
    ],
    positiveScenarios: ["若用得好，適合思考策略、整理方向"],
    negativeScenarios: ["若停不下來，容易焦慮、過度思考、睡不穩"],
    narrative: "這不是沒能力，而是大腦太在線，反而很難真正休息。",
    actionHint: "給思考一個結束點，別讓自己一直在線。",
  },
];

