/** S19 override: HEALTH 規則集 */
import type { InterpretationRule } from "../../interpretationRuleTypes.js";

export const HEALTH_RULES: InterpretationRule[] = [
  {
    id: "ziwei-quan-health",
    star: "紫微",
    transform: "權",
    palace: "疾厄宮",
    title: "壓力也要掌控",
    baseWeight: 1.1,
    eventType: ["壓力", "掌控", "身心負荷", "撐住"],
    baseScenarios: [
      "你會很想把壓力也控制好、安排好",
      "面對身心負荷時，傾向自己扛、自己調整",
      "即使累，也會先撐住，不太想示弱",
    ],
    positiveScenarios: [
      "若用得好，能把混亂壓力整理出秩序",
      "有機會透過主動調整，重新掌握節奏",
    ],
    negativeScenarios: [
      "容易因為太想掌控，而讓自己一直不能真正放鬆",
      "看起來能扛，實際上消耗很高",
    ],
    narrative: "你不是沒能力處理壓力，而是太習慣自己扛，反而不容易真正鬆下來。",
    actionHint: "先放下非必要控制，修復力才回得來。",
  },
  {
    id: "ziwei-ji-health",
    star: "紫微",
    transform: "忌",
    palace: "疾厄宮",
    title: "硬撐型耗損",
    baseWeight: 1.3,
    eventType: ["壓力", "硬撐", "耗損", "疲憊"],
    baseScenarios: [
      "壓力一來，你容易先撐住而不是先調整",
      "會有『我不能倒』的感覺",
      "身心負荷可能因責任感而累積",
    ],
    positiveScenarios: ["若能提早承認負荷，反而能重新分配壓力"],
    negativeScenarios: [
      "容易撐到過頭才發現自己不行了",
      "嚴重時可能出現明顯疲憊、失眠或持續緊繃",
    ],
    narrative: "最大的壓力不是事情本身，而是你太習慣把自己放在不能倒的位置。",
    actionHint: "先承認負荷，不要等撐不住才處理。",
  },
  {
    id: "tianji-quan-health",
    star: "天機",
    transform: "權",
    palace: "疾厄宮",
    title: "腦壓偏高",
    baseWeight: 1.1,
    eventType: ["思考", "焦慮", "精神活動", "停不下來"],
    baseScenarios: [
      "腦袋會特別忙，很難真正放鬆",
      "你會一直在想怎麼調整、怎麼解決、怎麼避免出錯",
      "壓力更多表現在思考與神經緊繃",
    ],
    positiveScenarios: ["若把這股能量用在整理與拆解問題，會有幫助"],
    negativeScenarios: [
      "容易想太多、停不下來、睡不穩",
      "精神上的累會比體力上的累更明顯",
    ],
    narrative: "你不是沒休息，而是腦袋沒有下班。",
    actionHint: "給思考一個結束點，不要讓自己一直在線。",
  },
  {
    id: "tianji-ji-health",
    star: "天機",
    transform: "忌",
    palace: "疾厄宮",
    title: "過度思考耗損",
    baseWeight: 1.3,
    eventType: ["焦慮", "反覆", "失眠", "想太多"],
    baseScenarios: [
      "容易反覆想、反覆擔心、反覆檢查",
      "壓力會卡在思緒裡，不容易排掉",
      "很多問題在腦中轉個不停",
    ],
    positiveScenarios: ["若願意記錄與外化，反而有機會把焦慮拆開"],
    negativeScenarios: [
      "容易精神疲乏、睡不好、神經緊",
      "久了會讓判斷力與恢復力一起下降",
    ],
    narrative: "累你的不只是事情，而是那些一直在腦中轉不停的未完成反應。",
    actionHint: "把腦內循環寫下來，不要只靠想。",
  },
  {
    id: "taiyang-ji-health",
    star: "太陽",
    transform: "忌",
    palace: "疾厄宮",
    title: "責任壓成消耗",
    baseWeight: 1.3,
    eventType: ["責任", "疲憊", "消耗", "過勞感"],
    baseScenarios: [
      "容易因責任感與持續付出而耗損",
      "會有一直在撐、一直在頂的感覺",
      "壓力可能來自外界期待，不一定來自自己",
    ],
    positiveScenarios: ["若願意重新分配責任，會明顯減壓"],
    negativeScenarios: [
      "容易出現過勞感、火氣、倦怠",
      "嚴重時會有『不想再撐』的念頭",
    ],
    narrative: "你累的不只是工作量，而是那種一直要負責、一直要照亮別人的位置。",
    actionHint: "不是每一份責任都該你全扛。",
  },
  {
    id: "taiyin-lu-health",
    star: "太陰",
    transform: "祿",
    palace: "疾厄宮",
    title: "修復力回來",
    baseWeight: 1.0,
    eventType: ["修復", "休息", "身心安撫", "恢復"],
    baseScenarios: [
      "比較容易找到讓自己舒服一點的方式",
      "身心狀態有機會慢慢回穩",
      "適合做修復、休息、睡眠與安頓",
    ],
    positiveScenarios: ["有利養回元氣、調整作息與內在安定感"],
    negativeScenarios: ["若太想躲回舒適區，也可能延後面對問題"],
    narrative: "這是一種把自己慢慢養回來、安放回來的能量。",
    actionHint: "先修復，再求效率。",
  },
  {
    id: "taiyin-ji-health",
    star: "太陰",
    transform: "忌",
    palace: "疾厄宮",
    title: "悶著耗",
    baseWeight: 1.2,
    eventType: ["情緒壓抑", "疲累", "低耗能", "悶住"],
    baseScenarios: [
      "很多累不是爆出來，而是悶著耗掉",
      "你可能不太想講，但身心會慢慢有感",
      "壓力常以低能量、低動力的方式表現",
    ],
    positiveScenarios: ["若能承認脆弱，反而比較容易進入修復"],
    negativeScenarios: [
      "容易出現低潮、失眠、無力、提不起勁",
      "若外部壓力再疊，會更難恢復",
    ],
    narrative: "最麻煩的不是大爆炸，而是那種悶悶地一直耗下去。",
    actionHint: "不要只忍，把悶住的東西找出口。",
  },
  {
    id: "jumen-ji-health",
    star: "巨門",
    transform: "忌",
    palace: "疾厄宮",
    title: "壓力變成內耗",
    baseWeight: 1.3,
    eventType: ["內耗", "焦慮", "懷疑", "睡不好"],
    baseScenarios: [
      "壓力容易變成反覆想、反覆懷疑、反覆檢討",
      "很多話沒講出去，但心裡一直在轉",
      "精神上的摩擦感會很明顯",
    ],
    positiveScenarios: ["若能把不安說出來，反而能鬆掉很多"],
    negativeScenarios: [
      "容易睡不好、想太多、越休息越累",
      "嚴重時連小事都會放大成壓力",
    ],
    narrative: "你不是脆弱，而是心裡那個一直說話的聲音太大了。",
    actionHint: "先停掉內心辯論，才有空間恢復。",
  },
  {
    id: "wuqu-ji-health",
    star: "武曲",
    transform: "忌",
    palace: "疾厄宮",
    title: "身體當成本在扛",
    baseWeight: 1.3,
    eventType: ["疲勞", "成本", "硬撐", "效率耗損"],
    baseScenarios: [
      "你可能會把身體當成資源去硬撐",
      "壓力會直接反映成疲勞、效率下降或恢復變慢",
      "很多事是靠意志撐，不是靠狀態撐",
    ],
    positiveScenarios: ["若提早休整，能避免更大的耗損"],
    negativeScenarios: [
      "容易累到影響產出與判斷",
      "久了會有『怎麼做都回不來』的感覺",
    ],
    narrative: "問題不只是累，而是你正在用自己的恢復力當成本。",
    actionHint: "別再拿身體補進度。",
  },
];

