/** S19 override: MONEY 規則集 */
import type { InterpretationRule } from "../../interpretationRuleTypes.js";

export const MONEY_RULES: InterpretationRule[] = [
  {
    id: "wuqu-lu-money",
    star: "武曲",
    transform: "祿",
    palace: "財帛宮",
    title: "回報進來",
    baseWeight: 1.2,
    eventType: ["收入", "回款", "績效", "資源入袋"],
    baseScenarios: [
      "收入、回報、績效面較有感",
      "錢的流動與結果比較看得到",
      "有把努力換成結果的感覺",
    ],
    positiveScenarios: [
      "有進帳、回款、加薪、案子入袋機會",
      "適合談價格、談成果、談實際回報",
    ],
    negativeScenarios: ["也可能只是忙著追錢、追績效與追結果"],
    narrative: "這是把努力變成結果、把成果變成錢的力量。",
    actionHint: "趁有結果時，把現金流也一起顧好。",
  },
  {
    id: "wuqu-ji-money",
    star: "武曲",
    transform: "忌",
    palace: "財帛宮",
    title: "現金流壓力",
    baseWeight: 1.3,
    eventType: ["金錢", "周轉", "卡款", "財務壓力"],
    baseScenarios: [
      "容易感受到金錢壓力與回報延遲",
      "支出、周轉、資源卡住會特別有感",
      "看得到帳面，不一定摸得到現金",
    ],
    positiveScenarios: ["若及早整理，有機會提早止血"],
    negativeScenarios: [
      "容易卡款、回報延遲、現金流緊",
      "嚴重時會進入財務保守期",
    ],
    narrative: "壓力不一定是沒錢，而是錢卡住、錢不夠靈活。",
    actionHint: "先顧現金流，不要只看帳面。",
  },
  {
    id: "tianfu-lu-money",
    star: "天府",
    transform: "祿",
    palace: "財帛宮",
    title: "資源累積",
    baseWeight: 1.0,
    eventType: ["金錢", "儲備", "穩定收入", "資源累積"],
    baseScenarios: [
      "比較容易把資源留住",
      "收入結構偏穩，不一定暴衝，但能慢慢累",
      "適合做資源盤點與留存",
    ],
    positiveScenarios: ["有累積存量、存款、庫存或穩定收入的傾向"],
    negativeScenarios: ["若過度求穩，也可能讓資金流動性不足"],
    narrative: "這不是暴利型，而是慢慢把東西留住、囤住、養起來的能量。",
    actionHint: "把可留存的東西留下來。",
  },
  {
    id: "tianfu-ji-money",
    star: "天府",
    transform: "忌",
    palace: "財帛宮",
    title: "資源卡庫",
    baseWeight: 1.2,
    eventType: ["金錢", "資源卡住", "庫存壓力", "留存問題"],
    baseScenarios: [
      "資源看似有，但不一定能順利動用",
      "庫存、存量、備用資源可能變成壓力",
      "留不住或用不好，都會形成耗損",
    ],
    positiveScenarios: ["若重新盤點結構，有機會看清資源黑洞"],
    negativeScenarios: ["容易有資金積壓、存貨壓力或資源配置失衡"],
    narrative: "問題不一定是沒有，而是留著也卡、放出去也不順。",
    actionHint: "盤點哪些是資產，哪些其實是包袱。",
  },
  {
    id: "taiyin-lu-money",
    star: "太陰",
    transform: "祿",
    palace: "財帛宮",
    title: "隱性資源進來",
    baseWeight: 1.0,
    eventType: ["金錢", "副收入", "被動收入", "女性資源"],
    baseScenarios: [
      "收入可能來自較隱性、較柔性的來源",
      "適合經營副收入、長尾收入或慢回收資源",
      "比較容易從照顧型、穩定型關係中得到支持",
    ],
    positiveScenarios: ["有副業、被動收入、女性客群或穩定資源機會"],
    negativeScenarios: ["太保守時也可能讓回收速度變慢"],
    narrative: "這種財不是衝出來的，而是慢慢養、慢慢累積起來的。",
    actionHint: "養長線收入，不要只盯短線快錢。",
  },
];

