/** S19 override: OUTPUT 規則集 */
import type { InterpretationRule } from "../../interpretationRuleTypes.js";

export const OUTPUT_RULES: InterpretationRule[] = [
  {
    id: "pojun-quan-output",
    star: "破軍",
    transform: "權",
    palace: "子女宮",
    title: "成果重組",
    baseWeight: 1.2,
    eventType: ["創作", "專案", "成果", "重做"],
    baseScenarios: [
      "輸出內容需要重新調整或重做",
      "創作或專案方向會有改動",
      "舊成果可能被推翻",
    ],
    positiveScenarios: ["有機會做出更強版本", "突破原本框架"],
    negativeScenarios: ["會有重工感或不穩定"],
    narrative: "不是壞掉，是升級前的拆掉。",
    actionHint: "敢砍，才有新東西。",
  },
  {
    id: "wenchang-ke-output",
    star: "文昌",
    transform: "科",
    palace: "子女宮",
    title: "成果整理與呈現",
    baseWeight: 1.1,
    eventType: ["創作", "輸出", "整理", "發表"],
    baseScenarios: [
      "輸出內容變得更清楚",
      "適合發表、寫作、整理成果",
      "內容更有結構",
    ],
    positiveScenarios: ["容易被理解與接受"],
    negativeScenarios: ["也可能只做到形式完整，深度仍要補"],
    narrative: "你做的東西開始變得可被理解。",
    actionHint: "把內容整理好再推出。",
  },
  {
    id: "wenchang-ji-output",
    star: "文昌",
    transform: "忌",
    palace: "子女宮",
    title: "輸出卡關",
    baseWeight: 1.3,
    eventType: ["創作", "卡關", "表達問題"],
    baseScenarios: [
      "輸出不順",
      "內容容易卡住或講不清楚",
      "做了但不滿意",
    ],
    positiveScenarios: ["若分段完成，有機會逐步解卡"],
    negativeScenarios: ["容易反覆修改", "成果延遲"],
    narrative: "不是沒東西，而是表達卡住。",
    actionHint: "先完成，再優化。",
  },
  {
    id: "tanlang-lu-output",
    star: "貪狼",
    transform: "祿",
    palace: "子女宮",
    title: "創作能量強",
    baseWeight: 1.1,
    eventType: ["創作", "靈感", "輸出", "表現"],
    baseScenarios: [
      "創作力上升",
      "容易產出內容",
      "表現慾變強",
    ],
    positiveScenarios: ["有作品產出", "內容吸引人"],
    negativeScenarios: ["也可能只重產量不重收斂"],
    narrative: "你會想做，也做得出來。",
    actionHint: "把靈感變作品。",
  },
  {
    id: "tanlang-ji-output",
    star: "貪狼",
    transform: "忌",
    palace: "子女宮",
    title: "創作分散",
    baseWeight: 1.2,
    eventType: ["創作", "分心", "不穩"],
    baseScenarios: ["想做很多", "但不集中", "產出不穩定"],
    positiveScenarios: ["若能鎖定一件，仍有機會完成"],
    negativeScenarios: ["容易半途而廢", "作品品質不一"],
    narrative: "靈感很多，但沒有收斂。",
    actionHint: "先做一件完整的。",
  },
];

