/** S19 override: PROPERTY 規則集 */
import type { InterpretationRule } from "../../interpretationRuleTypes.js";

export const PROPERTY_RULES: InterpretationRule[] = [
  {
    id: "wuqu-ke-property",
    star: "武曲",
    transform: "科",
    palace: "田宅宮",
    title: "資產制度化",
    baseWeight: 1.1,
    eventType: ["房產", "資產", "規劃", "整理"],
    baseScenarios: [
      "資產與房產適合靠制度與流程慢慢穩住",
      "適合整理帳、整理產權、整理配置",
      "這一塊會更重視效率與結構",
    ],
    positiveScenarios: ["有利買賣規劃、資產配置、正式整理", "容易讓原本混亂的狀況慢慢成形"],
    negativeScenarios: ["過程可能偏理性、辛苦，不一定立刻有舒服感"],
    narrative: "這不是暴衝型的變化，而是把資產這一塊越做越有秩序。",
    actionHint: "先把資產結構整理出來。",
  },
  {
    id: "wuqu-ji-property",
    star: "武曲",
    transform: "忌",
    palace: "田宅宮",
    title: "資產壓力點",
    baseWeight: 1.3,
    eventType: ["房產", "資產", "金錢壓力", "持有成本"],
    baseScenarios: [
      "房產、資產、持有成本或回報問題容易成為壓力點",
      "這一塊容易讓你感覺卡住或不划算",
      "錢可能壓在房子、空間、設備或留存資產裡",
    ],
    positiveScenarios: ["若及早整理，反而有機會看清真正該留與該砍的部分"],
    negativeScenarios: [
      "容易出現持有成本高、變現不易、資產回報不佳",
      "嚴重時會形成長期壓力",
    ],
    narrative: "問題不一定是沒有資產，而是資產正在變成壓力。",
    actionHint: "先問這些留存，到底是在養你，還是在拖你。",
  },
  {
    id: "wenchang-ke-property",
    star: "文昌",
    transform: "科",
    palace: "田宅宮",
    title: "文件與產權整理",
    baseWeight: 1.1,
    eventType: ["房產", "文件", "產權", "規則"],
    baseScenarios: [
      "房產、空間、資產文件與規則整理變重要",
      "適合處理產權、合約、紀錄、文書與行政流程",
      "這一塊適合靠資料與制度慢慢穩住",
    ],
    positiveScenarios: ["有利整合資料、補文件、補程序、補規則"],
    negativeScenarios: ["也可能只是文件先整理好，實際執行還在後面"],
    narrative: "這是一種靠文件、規則與整理，把基礎慢慢做穩的能量。",
    actionHint: "先把資料整理清楚，後面會省很多力。",
  },
  {
    id: "wenchang-ji-property",
    star: "文昌",
    transform: "忌",
    palace: "田宅宮",
    title: "產權與文件卡點",
    baseWeight: 1.2,
    eventType: ["房產", "文件", "合約風險", "行政卡關"],
    baseScenarios: [
      "容易在房產、產權、文件、行政流程上卡住",
      "合約、規則、紀錄或溝通細節可能出問題",
      "這一塊容易因資訊落差拖慢事情",
    ],
    positiveScenarios: ["若提早檢查，可以把後續風險先壓下來"],
    negativeScenarios: [
      "容易文件不齊、流程卡關、權責說不清",
      "嚴重時影響買賣、交付或規劃進度",
    ],
    narrative: "真正的雷不一定在大方向，而在文件、程序與細節。",
    actionHint: "不要只看大方向，細節才是真正的風險點。",
  },
  {
    id: "tianfu-lu-property",
    star: "天府",
    transform: "祿",
    palace: "田宅宮",
    title: "基礎留存變強",
    baseWeight: 1.0,
    eventType: ["房產", "基礎", "安定", "留存"],
    baseScenarios: [
      "對空間、居住、基礎與留存的掌握感提高",
      "比較容易把東西留住、守住",
      "有建立安穩基地的傾向",
    ],
    positiveScenarios: ["有利置產、整頓家務、建立生活基礎"],
    negativeScenarios: ["過度求穩時，也可能讓調整速度變慢"],
    narrative: "這是一種把基礎守穩、把生活盤面穩下來的能量。",
    actionHint: "先把根基顧好，外面的事才撐得住。",
  },
];

