/** S19 override: SELF 規則集 */
import type { InterpretationRule } from "../../interpretationRuleTypes.js";

export const SELF_RULES: InterpretationRule[] = [
  {
    id: "ziwei-quan-self",
    star: "紫微",
    transform: "權",
    palace: "命宮",
    title: "主導意識上升",
    baseWeight: 1.1,
    eventType: ["自我", "決策", "主導", "掌控"],
    baseScenarios: [
      "你會更想自己做決定，不太想被帶",
      "面對事情時，傾向主導而不是配合",
      "會有一種『我來定』的感覺",
    ],
    positiveScenarios: ["有利掌控局面、定方向、帶節奏"],
    negativeScenarios: ["也可能變成什麼都想自己決定，壓力變大"],
    narrative: "這個月你不太會等別人給答案，而是會想自己定調。",
    actionHint: "主導可以，但不用所有事都自己扛。",
  },
  {
    id: "ziwei-ji-self",
    star: "紫微",
    transform: "忌",
    palace: "命宮",
    title: "自我壓力放大",
    baseWeight: 1.3,
    eventType: ["自我", "壓力", "責任感", "內在要求"],
    baseScenarios: [
      "對自己的要求會變高",
      "容易覺得很多事要自己負責",
      "會有『我應該要更好』的壓力",
    ],
    positiveScenarios: ["若調整得當，能重新校正自己的位置"],
    negativeScenarios: [
      "容易對自己不滿、覺得不夠好",
      "壓力會變成內在負擔",
    ],
    narrative: "這個月最容易卡你的，不是外界，而是你對自己的要求。",
    actionHint: "把標準拉回現實，不要一直加碼。",
  },
  {
    id: "tianji-quan-self",
    star: "天機",
    transform: "權",
    palace: "命宮",
    title: "策略模式開啟",
    baseWeight: 1.1,
    eventType: ["思考", "策略", "判斷", "調整"],
    baseScenarios: [
      "你會一直在想怎麼調整、怎麼優化",
      "對變化很敏感",
      "決策會偏向分析與策略",
    ],
    positiveScenarios: ["有利規劃與調整方向"],
    negativeScenarios: ["想太多導致行動變慢"],
    narrative: "你會一直在想怎麼更好，但也容易因此卡住。",
    actionHint: "想夠就動，不要一直優化。",
  },
  {
    id: "tianji-ji-self",
    star: "天機",
    transform: "忌",
    palace: "命宮",
    title: "決策不穩",
    baseWeight: 1.3,
    eventType: ["猶豫", "反覆", "焦慮", "不確定"],
    baseScenarios: [
      "容易想很多，但很難做決定",
      "會反覆確認、反覆推翻",
      "對方向不太有把握",
    ],
    positiveScenarios: ["若能小步試錯，有機會打破猶豫"],
    negativeScenarios: [
      "容易拖延或錯過時機",
      "越想越亂",
    ],
    narrative: "問題不是沒有選擇，而是每個選擇看起來都不夠好。",
    actionHint: "先選一個可接受的，不要等完美答案。",
  },
  {
    id: "tanlang-lu-self",
    star: "貪狼",
    transform: "祿",
    palace: "命宮",
    title: "慾望與動力上升",
    baseWeight: 1.0,
    eventType: ["動力", "嘗試", "慾望", "行動"],
    baseScenarios: [
      "你會想嘗試更多東西",
      "動力與好奇心變強",
      "容易被新機會吸引",
    ],
    positiveScenarios: ["有利拓展與嘗試"],
    negativeScenarios: ["容易分心或做太多"],
    narrative: "這個月你會想要更多，也更願意去試。",
    actionHint: "選幾個重點，不要全部都要。",
  },
  {
    id: "tanlang-ji-self",
    star: "貪狼",
    transform: "忌",
    palace: "命宮",
    title: "分心與失焦",
    baseWeight: 1.2,
    eventType: ["分心", "慾望", "不穩", "情緒波動"],
    baseScenarios: [
      "容易想做很多，但抓不住重點",
      "情緒與慾望會影響判斷",
      "決策容易被當下感覺帶走",
    ],
    positiveScenarios: ["若能先鎖定主線，仍有機會收斂"],
    negativeScenarios: [
      "容易做錯選擇或後悔",
      "方向不穩",
    ],
    narrative: "問題不是沒機會，而是你抓不住哪個才重要。",
    actionHint: "先定一條主線，其它都先放。",
  },
  {
    id: "taiyin-lu-self",
    star: "太陰",
    transform: "祿",
    palace: "命宮",
    title: "內在穩定",
    baseWeight: 1.0,
    eventType: ["情緒", "穩定", "感受", "內在"],
    baseScenarios: [
      "情緒比較穩",
      "做決定會偏向安全與安定",
      "你會想讓自己舒服一點",
    ],
    positiveScenarios: ["有利穩定與調整"],
    negativeScenarios: ["可能過度追求舒適而拖延決策"],
    narrative: "這個月你會更重視內在感受，而不是外在速度。",
    actionHint: "讓自己穩，比追快更重要。",
  },
  {
    id: "taiyin-ji-self",
    star: "太陰",
    transform: "忌",
    palace: "命宮",
    title: "情緒內縮",
    baseWeight: 1.2,
    eventType: ["情緒", "退縮", "敏感", "低能量"],
    baseScenarios: [
      "情緒容易內縮",
      "不太想表達",
      "容易受影響但不說",
    ],
    positiveScenarios: ["若能釐清感受，仍有情緒出口"],
    negativeScenarios: [
      "容易悶著累",
      "判斷偏保守",
    ],
    narrative: "你會比較收，很多感受不會說出來。",
    actionHint: "至少讓自己知道自己在想什麼。",
  },
];

