/** S19 override: SERVANT 規則集 */
import type { InterpretationRule } from "../../interpretationRuleTypes.js";

export const SERVANT_RULES: InterpretationRule[] = [
  {
    id: "lianzhen-lu-servant",
    star: "廉貞",
    transform: "祿",
    palace: "僕役宮",
    title: "合作端有推力",
    baseWeight: 1.0,
    eventType: ["客戶", "合作端", "執行資源", "人際推進"],
    baseScenarios: [
      "合作端、客戶端或協作方會帶來推進力",
      "你會感受到外部人脈或執行資源變得可用",
      "有人願意配合、幫忙或往前推",
    ],
    positiveScenarios: [
      "有利找幫手、找協作、找執行資源",
      "對接的人有機會成為助力",
    ],
    negativeScenarios: ["資源進來的同時，也可能帶來界線與控制議題"],
    narrative: "不是你一個人在推，而是執行端開始有力道了。",
    actionHint: "有人幫時，先把邊界與分工訂清楚。",
  },
  {
    id: "lianzhen-ji-servant",
    star: "廉貞",
    transform: "忌",
    palace: "僕役宮",
    title: "合作端難搞",
    baseWeight: 1.3,
    eventType: ["客戶", "下游", "合作衝突", "執行拉扯"],
    baseScenarios: [
      "問題容易出在客戶、合作方、下游或執行端",
      "你會感覺對方有自己的立場、情緒或控制感",
      "事情卡的原因，未必在你，而在對接的人",
    ],
    positiveScenarios: ["若把規則講清楚，仍有機會重新整理合作模式"],
    negativeScenarios: [
      "容易出現互不相讓、互不信任、互相拖累",
      "嚴重時可能拆夥、停合作或乾脆不做",
    ],
    narrative: "不是事情本身太難，而是合作端的界線、權責與情緒開始變難搞。",
    actionHint: "先處理人，再處理事。",
  },
  {
    id: "jumen-lu-servant",
    star: "巨門",
    transform: "祿",
    palace: "僕役宮",
    title: "談出合作空間",
    baseWeight: 1.0,
    eventType: ["客戶", "溝通", "談判", "合作空間"],
    baseScenarios: [
      "很多事情有機會透過溝通談出空間",
      "對接、討論、說法與談判會成為關鍵",
      "某些原本卡住的合作，可能因對話而打開",
    ],
    positiveScenarios: ["有利談條件、談資源、談合作方式"],
    negativeScenarios: ["話變多的同時，也可能帶來反覆與爭辯"],
    narrative: "合作能不能成，很多時候取決於你怎麼談。",
    actionHint: "先把關鍵條件講清楚。",
  },
  {
    id: "jumen-ji-servant",
    star: "巨門",
    transform: "忌",
    palace: "僕役宮",
    title: "對接誤差",
    baseWeight: 1.3,
    eventType: ["客戶", "誤會", "溝通不良", "執行錯位"],
    baseScenarios: [
      "對接過程容易出現誤解、漏接或說法不同",
      "你以為對方懂了，其實沒對齊",
      "很多問題會在交付、協作或回饋時浮出來",
    ],
    positiveScenarios: ["若願意重講一次、重對一次，仍可避免擴大"],
    negativeScenarios: [
      "容易越講越歪、越做越偏",
      "嚴重時會變成明顯返工或互相抱怨",
    ],
    narrative: "合作端最麻煩的不是做不到，而是大家以為自己在講同一件事。",
    actionHint: "不要只問『懂嗎』，要確認『是不是同一個理解』。",
  },
  {
    id: "zuofu-lu-servant",
    star: "左輔",
    transform: "祿",
    palace: "僕役宮",
    title: "執行助力進來",
    baseWeight: 0.9,
    eventType: ["團隊", "協作", "支援", "補位"],
    baseScenarios: [
      "會比較容易遇到願意補位與支援的人",
      "執行面不一定輕鬆，但有人能幫你分擔",
      "你不需要所有事都自己扛",
    ],
    positiveScenarios: ["有利找助理、找副手、找可靠的協作人"],
    negativeScenarios: ["也可能因此更依賴少數關鍵幫手"],
    narrative: "這是一種你終於不用一個人全扛的狀態。",
    actionHint: "把能分出去的，真的分出去。",
  },
  {
    id: "youbi-lu-servant",
    star: "右弼",
    transform: "祿",
    palace: "僕役宮",
    title: "人和補上來",
    baseWeight: 0.9,
    eventType: ["合作", "協調", "人和", "關係緩衝"],
    baseScenarios: [
      "合作中的協調感比較容易上來",
      "即使有問題，也比較容易找到人和的解法",
      "有人會願意幫忙協調、潤滑與緩衝",
    ],
    positiveScenarios: ["有利修復合作氣氛、拉近距離、減少摩擦"],
    negativeScenarios: ["也可能讓你誤以為只靠好相處就能解決結構問題"],
    narrative: "這不是硬實力突然變強，而是人和補上來了。",
    actionHint: "有人和時，順便把結構也補起來。",
  },
  {
    id: "tanlang-ji-servant",
    star: "貪狼",
    transform: "忌",
    palace: "僕役宮",
    title: "合作端雜訊多",
    baseWeight: 1.2,
    eventType: ["客戶", "應酬", "雜訊", "複雜局"],
    baseScenarios: [
      "合作端容易很熱鬧，但不一定有效率",
      "人很多、意見很多、需求很多，會讓你覺得很雜",
      "有時不是事情難，而是對接端太多聲音",
    ],
    positiveScenarios: ["若你能收斂對接窗口，會明顯清爽很多"],
    negativeScenarios: [
      "容易出現需求漂移、反覆改動、表面熱絡但實際拖累",
      "也可能有不必要的應酬或人情壓力",
    ],
    narrative: "問題不是沒人，而是人一多，雜訊也一起進來。",
    actionHint: "縮小窗口，別讓所有人都能改你。",
  },
  {
    id: "tianxiang-ke-servant",
    star: "天相",
    transform: "科",
    palace: "僕役宮",
    title: "合作規則補上",
    baseWeight: 1.0,
    eventType: ["合作", "分工", "制度", "對接規則"],
    baseScenarios: [
      "合作端最需要的是把流程、規則與分工補齊",
      "適合建立窗口、確認權責、重新定交付方式",
      "只要制度補上，很多摩擦都能下降",
    ],
    positiveScenarios: ["有利讓團隊與客戶端進入比較可控的狀態"],
    negativeScenarios: ["若只講人情不講規則，後面還是會再亂一次"],
    narrative: "這不是靠默契的局，而是靠規則會更順的局。",
    actionHint: "把合作規則寫下來，不要只靠記得。",
  },
];

