/** S19 override: SIBLING 規則集 */
import type { InterpretationRule } from "../../interpretationRuleTypes.js";

export const SIBLING_RULES: InterpretationRule[] = [
  {
    id: "lianzhen-lu-sibling",
    star: "廉貞",
    transform: "祿",
    palace: "兄弟宮",
    title: "合作資源帶張力",
    baseWeight: 1.1,
    eventType: ["合作", "同儕", "資源", "關係推進"],
    baseScenarios: [
      "合作關係中容易出現可用資源或新的推進機會",
      "你會更明顯感受到人脈、同儕、平行資源的拉力",
      "某些原本卡住的合作，可能因關係推動而動起來",
    ],
    positiveScenarios: [
      "容易遇到能幫你推進事情的人",
      "合作有機會帶來實際好處或新資源",
      "關係中的界線若談清楚，反而更能互利",
    ],
    negativeScenarios: [
      "資源進來的同時，也容易夾帶控制感或關係壓力",
      "合作會有互相拉扯、誰說了算的問題",
    ],
    narrative: "這不是單純有人幫你，而是合作本身帶著資源，也帶著張力。",
    actionHint: "能合作，但先把界線談清楚。",
  },
  {
    id: "lianzhen-ji-sibling",
    star: "廉貞",
    transform: "忌",
    palace: "兄弟宮",
    title: "合作界線衝突",
    baseWeight: 1.3,
    eventType: ["合作", "衝突", "界線", "翻臉風險"],
    baseScenarios: [
      "合作關係容易出現界線不清、控制感過強或彼此不服的狀況",
      "同儕或夥伴之間容易有試探、拉扯、較勁",
      "原本講好的事，可能因權責或情緒問題變得卡",
    ],
    positiveScenarios: ["若願意把規則講清楚，反而有機會重整合作方式"],
    negativeScenarios: ["容易因一件事累積成不信任", "嚴重時可能冷掉、拆夥、翻臉或不再往來"],
    narrative: "問題不一定是事情本身，而是合作裡的界線、控制感與不安全感變得太重。",
    actionHint: "先把權責切清楚，不要靠默契硬撐。",
  },
  {
    id: "jumen-lu-sibling",
    star: "巨門",
    transform: "祿",
    palace: "兄弟宮",
    title: "說法帶來資源",
    baseWeight: 1.0,
    eventType: ["合作", "談判", "說服", "資訊資源"],
    baseScenarios: [
      "合作關係中，說法、談判、資訊交換會帶來機會",
      "有人脈或資源會因溝通而進來",
      "適合把想法講出來，透過討論換資源",
    ],
    positiveScenarios: ["容易談成合作、談到條件、談出空間", "透過對話可以找到彼此的利益交集"],
    negativeScenarios: ["好處雖然能談出來，但也容易伴隨意見很多、嘴上交鋒"],
    narrative: "這是一種靠說法、資訊與談判把資源引進來的力量。",
    actionHint: "把立場講清楚，比先討好更有用。",
  },
  {
    id: "jumen-ji-sibling",
    star: "巨門",
    transform: "忌",
    palace: "兄弟宮",
    title: "口舌與不信任",
    baseWeight: 1.3,
    eventType: ["合作", "爭議", "誤解", "翻舊帳"],
    baseScenarios: [
      "同儕或合作關係裡容易因說法不同而起爭議",
      "很容易出現誤會、懷疑、話沒講清楚的問題",
      "舊帳、舊話題或以前的不滿容易被翻出來",
    ],
    positiveScenarios: ["若願意把問題攤開談，反而能看見真正的不滿在哪"],
    negativeScenarios: ["容易越講越糟、越辯越僵", "合作可能從小誤會累積成明顯裂痕"],
    narrative: "問題不只在事情，而是在彼此對事情的理解、說法與信任感都開始鬆動。",
    actionHint: "先確認彼此在講的是不是同一件事。",
  },
  {
    id: "tianxiang-ke-sibling",
    star: "天相",
    transform: "科",
    palace: "兄弟宮",
    title: "合作規則成形",
    baseWeight: 1.0,
    eventType: ["合作", "規則", "分工", "平衡"],
    baseScenarios: [
      "合作關係更需要規則、分工與對應",
      "原本模糊的合作模式，適合慢慢制度化",
      "適合重新整理誰負責什麼、誰對應什麼",
    ],
    positiveScenarios: ["分工變清楚後，合作會更順", "有利建立可長可久的合作模式"],
    negativeScenarios: ["若太講規則，也可能讓互動變得有點僵"],
    narrative: "這是一種讓合作慢慢有秩序、有分工、有對位的能量。",
    actionHint: "把對位理清楚，默契才撐得久。",
  },
  {
    id: "tianxiang-ji-sibling",
    star: "天相",
    transform: "忌",
    palace: "兄弟宮",
    title: "失衡的合作關係",
    baseWeight: 1.2,
    eventType: ["合作", "失衡", "不公平", "分工失準"],
    baseScenarios: [
      "合作裡容易出現不公平、失衡或彼此心裡不平的感覺",
      "表面上還在配合，實際上已經開始不對位",
      "分工與回報可能不成比例",
    ],
    positiveScenarios: ["若願意面對不平衡，反而有機會重整合作關係"],
    negativeScenarios: [
      "容易出現『我做比較多』『為什麼都是我配合』的累積感",
      "嚴重時會讓合作慢慢失去信任",
    ],
    narrative: "問題不一定是衝突，而是關係裡的不平衡正在默默累積。",
    actionHint: "覺得不平衡時，要說，不要悶著配合。",
  },
  {
    id: "tanlang-lu-sibling",
    star: "貪狼",
    transform: "祿",
    palace: "兄弟宮",
    title: "人脈擴張",
    baseWeight: 1.0,
    eventType: ["人脈", "社交", "合作機會", "資源擴張"],
    baseScenarios: [
      "人際與合作圈容易擴大",
      "同儕、朋友、客戶、合作邀約變多",
      "容易因社交互動而得到新機會",
    ],
    positiveScenarios: ["有利拓展關係網、拉資源、認識新合作對象"],
    negativeScenarios: ["圈子變大時，也容易出現應酬感與分心感"],
    narrative: "這是一種人脈活起來、互動變多、資源開始流動的狀態。",
    actionHint: "可以擴，但要分清楚誰是關鍵人。",
  },
  {
    id: "tanlang-ji-sibling",
    star: "貪狼",
    transform: "忌",
    palace: "兄弟宮",
    title: "人際消耗",
    baseWeight: 1.2,
    eventType: ["人際", "消耗", "比較", "複雜關係"],
    baseScenarios: [
      "同儕與合作圈容易變得複雜",
      "社交、人情、比較心、競爭感會帶來消耗",
      "容易有表面熱絡、實際疲累的感覺",
    ],
    positiveScenarios: ["若能收斂圈子，反而會看見誰真正值得留"],
    negativeScenarios: [
      "容易有八卦、比較、情緒性互動或無效應酬",
      "合作中也可能因慾望與利益出現糾結",
    ],
    narrative: "不是沒有人，而是人一多，雜訊、比較與消耗也一起上來。",
    actionHint: "縮小無效社交，把力氣留給真合作。",
  },
  {
    id: "zuofu-lu-sibling",
    star: "左輔",
    transform: "祿",
    palace: "兄弟宮",
    title: "合作助力到位",
    baseWeight: 0.9,
    eventType: ["合作", "支援", "協作", "助力"],
    baseScenarios: [
      "比較容易遇到願意配合、幫忙、補位的人",
      "合作中會感覺有人站在你這邊",
      "一些事情可以靠協作而變順",
    ],
    positiveScenarios: ["有利建立互補型合作", "容易找到願意幫忙推進的人"],
    negativeScenarios: ["也可能因此更依賴特定的人力支援"],
    narrative: "這是一種合作補位感變強、有人能幫你撐一下的狀態。",
    actionHint: "有人幫時，記得把協作節點也整理好。",
  },
];

