/** S19 override: SPOUSE 規則集 */
import type { InterpretationRule } from "../../interpretationRuleTypes.js";

export const SPOUSE_RULES: InterpretationRule[] = [
  {
    id: "wenchang-ke-spouse",
    star: "文昌",
    transform: "科",
    palace: "夫妻宮",
    title: "關係制度化",
    baseWeight: 1.1,
    eventType: ["感情", "承諾", "婚姻", "共識"],
    baseScenarios: [
      "會開始談關係定位與未來安排",
      "感情中的規劃與共識感變得更重要",
      "適合把一些關係中的話講清楚",
    ],
    positiveScenarios: [
      "有談婚論嫁的可能",
      "關係可能進入較正式或較穩定的規劃期",
      "雙方更願意把未來放進討論",
    ],
    negativeScenarios: [
      "表面看似理性穩定，但也可能只是形式先到位",
      "容易停留在談條件，未必真的談到內心",
    ],
    narrative: "感情關係中的規劃、共識與制度感會上升，容易進入比較正式的討論。",
    actionHint: "把話講清楚，但不要只停在形式。",
  },
  {
    id: "wenchang-ji-spouse",
    star: "文昌",
    transform: "忌",
    palace: "夫妻宮",
    title: "關係溝通卡點",
    baseWeight: 1.2,
    eventType: ["感情", "溝通", "誤會", "分離風險"],
    baseScenarios: [
      "伴侶間容易出現說法不同、理解不同的情況",
      "訊息、文字、承諾或討論內容容易造成誤會",
      "舊問題可能被重新翻出來談",
    ],
    positiveScenarios: [
      "若原本穩定，這比較像一次需要面對的磨合",
      "有機會透過一次誠實溝通重新校正",
    ],
    negativeScenarios: [
      "若原本已有壓力，容易冷戰、疏離、分開思考",
      "嚴重時可能談到分手、分居、離婚等議題",
    ],
    narrative: "關係中的問題往往不是突然爆掉，而是溝通與認知落差慢慢累積。",
    actionHint: "先釐清理解，不要急著分輸贏。",
  },
  {
    id: "wenqu-ke-spouse",
    star: "文曲",
    transform: "科",
    palace: "夫妻宮",
    title: "關係氛圍修復",
    baseWeight: 1.0,
    eventType: ["感情", "修復", "柔化", "和好"],
    baseScenarios: [
      "關係中的情緒氣氛有機會被修順",
      "比較容易願意好好談感受",
      "適合修補原本有點距離的互動",
    ],
    positiveScenarios: ["有利和好、修復、重新靠近", "適合安排有儀式感的互動"],
    negativeScenarios: ["也可能停留在好看、好聽，未必真正碰到核心問題"],
    narrative: "這是一種先修氛圍、再修關係的能量，柔和會比硬碰硬有效。",
    actionHint: "先把氣氛修順，再談問題。",
  },
  {
    id: "wenqu-ji-spouse",
    star: "文曲",
    transform: "忌",
    palace: "夫妻宮",
    title: "情緒誤讀",
    baseWeight: 1.2,
    eventType: ["感情", "情緒", "冷戰", "疏離"],
    baseScenarios: [
      "容易情緒化解讀對方的話",
      "明明在乎，卻表達成受傷或抱怨",
      "關係裡的失落感會被放大",
    ],
    positiveScenarios: ["若願意停下來談感受，反而能更看懂彼此真正卡在哪"],
    negativeScenarios: ["容易悶住、不說、冷戰", "若原本已經疏離，可能進一步情感斷線"],
    narrative: "問題不只是說了什麼，而是彼此怎麼感受、怎麼解讀。",
    actionHint: "先說感受，不要先做判決。",
  },
  {
    id: "lianzhen-lu-spouse",
    star: "廉貞",
    transform: "祿",
    palace: "夫妻宮",
    title: "關係吸引與推進",
    baseWeight: 1.0,
    eventType: ["感情", "吸引", "靠近", "推進"],
    baseScenarios: [
      "關係張力與吸引力提高",
      "容易出現更靠近、表態或推進的情況",
      "感情互動比較有火花",
    ],
    positiveScenarios: ["有發展感情、確認關係的可能", "互動變得更有真實拉力"],
    negativeScenarios: ["吸引力增加的同時，也容易帶出界線問題"],
    narrative: "這不是安穩型的甜，而是有張力、有吸引、會推動關係前進的互動。",
    actionHint: "靠近可以，但界線也要講清楚。",
  },
  {
    id: "lianzhen-ji-spouse",
    star: "廉貞",
    transform: "忌",
    palace: "夫妻宮",
    title: "界線與控制衝突",
    baseWeight: 1.3,
    eventType: ["感情", "控制", "爭執", "分離風險"],
    baseScenarios: [
      "容易因界線、掌控感、忠誠感產生拉扯",
      "感情裡的試探與不安全感升高",
      "容易出現是非、懷疑或控制感",
    ],
    positiveScenarios: ["若願意談清楚，反而能重新劃界線"],
    negativeScenarios: ["若原本已有裂痕，容易走向強烈對立", "嚴重時可能進入破裂或分開"],
    narrative: "問題不是沒有感情，而是關係裡的界線與掌控感變得太強。",
    actionHint: "別用控制換安全感。",
  },
  {
    id: "tanlang-lu-spouse",
    star: "貪狼",
    transform: "祿",
    palace: "夫妻宮",
    title: "桃花與熱度上升",
    baseWeight: 1.0,
    eventType: ["桃花", "曖昧", "戀愛", "熱度"],
    baseScenarios: [
      "感情互動變熱",
      "容易有桃花、曖昧或被注意",
      "關係裡的激情感變強",
    ],
    positiveScenarios: ["單身者容易有發展機會", "有伴者關係熱度提高"],
    negativeScenarios: ["也可能帶來多線互動或誘惑"],
    narrative: "機會不只變多，心動也會變多，重點變成你要不要定下來。",
    actionHint: "先分清楚是心動，還是分心。",
  },
  {
    id: "tanlang-ji-spouse",
    star: "貪狼",
    transform: "忌",
    palace: "夫妻宮",
    title: "欲望失衡",
    baseWeight: 1.3,
    eventType: ["桃花風險", "誘惑", "糾纏", "破局風險"],
    baseScenarios: [
      "容易因欲望、選擇過多或外在吸引而失衡",
      "感情裡容易出現比較、不安與搖擺",
      "關係可能受外在誘惑影響",
    ],
    positiveScenarios: ["若能自覺，反而能看清自己真正要的是什麼"],
    negativeScenarios: [
      "容易出現第三者、曖昧糾纏或感情不專",
      "嚴重時可能讓關係破局",
    ],
    narrative: "不是沒有感情，而是心不夠定，關係容易被外在誘惑或內在慾望打亂。",
    actionHint: "先定心，再談承諾。",
  },
  {
    id: "taiyin-lu-spouse",
    star: "太陰",
    transform: "祿",
    palace: "夫妻宮",
    title: "情感滋養",
    baseWeight: 1.0,
    eventType: ["感情", "照顧", "安定", "陪伴"],
    baseScenarios: [
      "關係裡的照顧感與包容感提升",
      "比較容易想安定下來",
      "互動偏向留住與陪伴",
    ],
    positiveScenarios: ["適合同居、談未來、讓關係更穩", "比較容易感受到被照顧與被接住"],
    negativeScenarios: ["也可能過度依賴安穩感，不想碰真正的問題"],
    narrative: "這是一種想把關係留住、安頓下來、慢慢養好的能量。",
    actionHint: "把溫柔落實成具體行動。",
  },
  {
    id: "taiyin-ji-spouse",
    star: "太陰",
    transform: "忌",
    palace: "夫妻宮",
    title: "情感退縮",
    baseWeight: 1.2,
    eventType: ["冷淡", "退縮", "失望", "疏離"],
    baseScenarios: [
      "容易覺得沒被理解、沒被安放",
      "關係互動比較容易退縮",
      "心裡失望感比表面衝突更明顯",
    ],
    positiveScenarios: ["若能談清楚需求，仍有修復空間"],
    negativeScenarios: ["容易進入冷淡、失望、疏離", "若長期累積，可能走向分開"],
    narrative: "傷不一定在表面，而是在心裡慢慢退掉。",
    actionHint: "把需要說出來，不要只等對方自己懂。",
  },
];

