/** S19 override: TRAVEL 規則集 */
import type { InterpretationRule } from "../../interpretationRuleTypes.js";

export const TRAVEL_RULES: InterpretationRule[] = [
  {
    id: "tianji-quan-travel",
    star: "天機",
    transform: "權",
    palace: "遷移宮",
    title: "外部策略主導",
    baseWeight: 1.2,
    eventType: ["市場", "策略", "變動", "決策"],
    baseScenarios: [
      "外部環境變動變多，需要你不斷調整策略",
      "你會更主動去判斷方向、做選擇",
      "很多事情需要臨場反應與即時決策",
    ],
    positiveScenarios: ["有利做策略轉向、優化方向", "適合主動出擊、調整布局"],
    negativeScenarios: ["變動太多時容易焦慮或判斷疲勞"],
    narrative: "外部不是穩定給答案，而是逼你邊走邊判斷。",
    actionHint: "決策可以快，但原則要穩。",
  },
  {
    id: "tianji-ji-travel",
    star: "天機",
    transform: "忌",
    palace: "遷移宮",
    title: "方向不穩",
    baseWeight: 1.3,
    eventType: ["市場", "混亂", "錯判", "反覆"],
    baseScenarios: [
      "外部方向容易反覆或資訊混亂",
      "你可能覺得怎麼選都不太對",
      "容易出現判斷失誤或過度猶豫",
    ],
    positiveScenarios: ["若放慢決策，有機會避開錯誤方向"],
    negativeScenarios: ["容易走冤枉路或白忙一段", "市場反應與預期落差大"],
    narrative: "不是你不會判斷，而是訊號本身就很亂。",
    actionHint: "少做多看，先確認再行動。",
  },
  {
    id: "taiyang-lu-travel",
    star: "太陽",
    transform: "祿",
    palace: "遷移宮",
    title: "外部曝光機會",
    baseWeight: 1.1,
    eventType: ["曝光", "市場", "機會", "對外發展"],
    baseScenarios: [
      "外部可見度提高，容易被看見",
      "有對外發展、曝光或代表性的機會",
      "市場會給你回應",
    ],
    positiveScenarios: ["有利拓展市場、曝光品牌", "容易被看見與認可"],
    negativeScenarios: ["曝光同時也會帶來壓力"],
    narrative: "你會被放到更亮的地方，機會與壓力一起來。",
    actionHint: "站上去時，準備好承接。",
  },
  {
    id: "taiyang-ji-travel",
    star: "太陽",
    transform: "忌",
    palace: "遷移宮",
    title: "外部壓力與評價",
    baseWeight: 1.3,
    eventType: ["壓力", "市場評價", "曝光風險"],
    baseScenarios: [
      "外界評價、期待或壓力變明顯",
      "容易被放大檢視",
      "對外表現容易被挑毛病",
    ],
    positiveScenarios: ["若能穩住節奏，有機會重新定義形象"],
    negativeScenarios: ["容易被誤解、被放大或被質疑", "壓力感會很直接"],
    narrative: "問題不只是事情，而是外界怎麼看你。",
    actionHint: "先穩住節奏，不要急著證明。",
  },
  {
    id: "tanlang-lu-travel",
    star: "貪狼",
    transform: "祿",
    palace: "遷移宮",
    title: "機會與誘惑增加",
    baseWeight: 1.1,
    eventType: ["機會", "桃花", "市場", "多選擇"],
    baseScenarios: [
      "外部機會變多",
      "容易接觸新圈子、新人、新案子",
      "選擇變多",
    ],
    positiveScenarios: ["有利拓展與嘗試", "容易遇到新資源"],
    negativeScenarios: ["選擇太多容易分心"],
    narrative: "外面變得很熱鬧，但也更容易迷失。",
    actionHint: "不是每個機會都要接。",
  },
  {
    id: "tanlang-ji-travel",
    star: "貪狼",
    transform: "忌",
    palace: "遷移宮",
    title: "外部混亂與誘惑",
    baseWeight: 1.3,
    eventType: ["混亂", "誘惑", "錯選", "複雜局"],
    baseScenarios: [
      "外部環境變得複雜",
      "容易遇到誘惑或不乾淨的機會",
      "判斷容易被影響",
    ],
    positiveScenarios: ["若收斂選擇，有機會避開錯誤方向"],
    negativeScenarios: ["容易選錯方向或被帶偏", "市場資訊不單純"],
    narrative: "問題不是沒有機會，而是機會太亂。",
    actionHint: "寧可少做，不要亂接。",
  },
  {
    id: "pojun-quan-travel",
    star: "破軍",
    transform: "權",
    palace: "遷移宮",
    title: "外部重組",
    baseWeight: 1.2,
    eventType: ["變動", "重組", "轉換"],
    baseScenarios: [
      "外部環境會逼你改變",
      "原本模式可能被打掉重來",
      "需要重新適應新局",
    ],
    positiveScenarios: ["有利突破舊格局"],
    negativeScenarios: ["變動太大時會不安"],
    narrative: "不是優化，是直接換一個玩法。",
    actionHint: "不要守舊局。",
  },
];

